In [81]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [82]:

data_set = pd.read_csv('/Users/sruthiparol/Desktop/Breast_Cancer.csv')


data_set.head()  


X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [83]:
data_set.head()  


id\tradius_mean\ttexture_mean\tperimeter_mean\tarea_mean\tsmoothness_mean\tcompactness_mean\tconcavity_mean\tconcave points_mean\tsymmetry_mean\tfractal_dimension_mean\tradius_se\ttexture_se\tperimeter_se\tarea_se\tsmoothness_se\tcompactness_se\tconcavity_se\tconcave points_se\tsymmetry_se\tfractal_dimension_se\tradius_worst\ttexture_worst\tperimeter_worst\tarea_worst\tsmoothness_worst\tcompactness_worst\tconcavity_worst\tconcave points_worst\tsymmetry_worst\tfractal_dimension_worst\tdiagnosis
0  842302\t17.99\t10.38\t122.8\t1001\t0.1184\t0.2...                                                                                                                                                                                                                                                                                                                                                                                                                                                                
1  842517\t20.57\t17.77\t132.9\t1326\t0.08474\t0....                                                                                                                                                                                                                                                                                                                                                                                                                                                                
2  84300903\t19.69\t21.25\t130\t1203\t0.1096\t0.1...                                                                                                                                                                                                                                                                                                                                                                                                                                                                
3  84348301\t11.42\t20.38\t77.58\t386.1\t0.1425\t...                                                                                                                                                                                                                                                                                                                                                                                                                                                                
4  84358402\t20.29\t14.34\t135.1\t1297\t0.1003\t0...

In [84]:
print(X)

[]


In [85]:
print(y)

['842302\t17.99\t10.38\t122.8\t1001\t0.1184\t0.2776\t0.3001\t0.1471\t0.2419\t0.07871\t1.095\t0.9053\t8.589\t153.4\t0.006399\t0.04904\t0.05373\t0.01587\t0.03003\t0.006193\t25.38\t17.33\t184.6\t2019\t0.1622\t0.6656\t0.7119\t0.2654\t0.4601\t0.1189\t1'
 '842517\t20.57\t17.77\t132.9\t1326\t0.08474\t0.07864\t0.0869\t0.07017\t0.1812\t0.05667\t0.5435\t0.7339\t3.398\t74.08\t0.005225\t0.01308\t0.0186\t0.0134\t0.01389\t0.003532\t24.99\t23.41\t158.8\t1956\t0.1238\t0.1866\t0.2416\t0.186\t0.275\t0.08902\t1'
 '84300903\t19.69\t21.25\t130\t1203\t0.1096\t0.1599\t0.1974\t0.1279\t0.2069\t0.05999\t0.7456\t0.7869\t4.585\t94.03\t0.00615\t0.04006\t0.03832\t0.02058\t0.0225\t0.004571\t23.57\t25.53\t152.5\t1709\t0.1444\t0.4245\t0.4504\t0.243\t0.3613\t0.08758\t1'
 '84348301\t11.42\t20.38\t77.58\t386.1\t0.1425\t0.2839\t0.2414\t0.1052\t0.2597\t0.09744\t0.4956\t1.156\t3.445\t27.23\t0.00911\t0.07458\t0.05661\t0.01867\t0.05963\t0.009208\t14.91\t26.5\t98.87\t567.7\t0.2098\t0.8663\t0.6869\t0.2575\t0.6638\t0.173\t1'
 '8

In [86]:
#handling Missing Data
from sklearn.impute import SimpleImputer

print("Shape of X:", X.shape)

if X.shape[1] > 0:
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    
    # Make sure the column indices are valid
    # If X has fewer than 3 columns, adjust the slice accordingly
    num_cols = min(3, X.shape[1])
    
    imputer.fit(X[:, 0:num_cols])
    X[:, 0:num_cols] = imputer.transform(X[:, 0:num_cols])
else:
    print("Error: X has no columns to impute")

Shape of X: (569, 0)
Error: X has no columns to impute


In [87]:
print(X)

[]


In [114]:
# First, check if X is properly initialized and has data
print(f"Shape of X: {X.shape}")

# If X is empty, initialize it with some data
if X.size == 0 or X.shape[1] == 0:
    
    
    print("X is empty. Please initialize X with data before proceeding.")
else:
   
    num_columns = X.shape[1]
    print(f"X has {num_columns} columns")
    
    # Choose a valid column index (first column if available)
    if num_columns > 0:
        col_idx = 0  # Use the first column
        imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
        imputer.fit(X[:, col_idx].reshape(-1, 1))
        X[:, col_idx] = imputer.transform(X[:, col_idx].reshape(-1, 1)).flatten()
        print(f"Imputation completed for column {col_idx}")
    
   

Shape of X: (569, 31)
X has 31 columns


InvalidIndexError: (slice(None, None, None), 0)

In [89]:
print(X)

[]


In [90]:
#Encoding Categorical Data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [91]:
# Import necessary libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Create sample data - uncomment one of these options
X = np.array([['red'], ['blue'], ['green'], ['red']])  # Single column example
# X = np.array([['red', 1], ['blue', 2], ['green', 3], ['red', 4]])  # Two column example


print(X.shape)  

# Correct the ColumnTransformer by ensuring column indices are valid
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Use [0] for the first column
    remainder='passthrough'
)

# Apply the transformation
X_transformed = ct.fit_transform(X)  # Store result in a new variable to avoid confusion

# Convert to numpy array if needed (fit_transform already returns numpy array in newer sklearn versions)
X_transformed = np.array(X_transformed)

# Now X_transformed contains the transformed data
print(X_transformed)

(4, 1)
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [92]:
print(X)

[['red']
 ['blue']
 ['green']
 ['red']]


In [93]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [94]:
print(y)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [95]:
#Splitting data into Test set& Training set
from sklearn.model_selection import train_test_split


print(data_set.columns)

column_names_string = data_set.columns[0]

true_column_names = column_names_string.split('\t')
data_set_fixed = data_set.iloc[:, 0].str.split('\t', expand=True)

# Assign the true column names to the new DataFrame
data_set_fixed.columns = true_column_names

# --- Apply the splitting logic to the FIXED DataFrame ---
data_set = data_set_fixed
target_column = 'diagnosis' 


X = data_set.drop(target_column, axis=1)  
y = data_set[target_column]  # Target variable

# Check the shapes to ensure they match
print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

# Now both X and y should have the same number of samples (rows)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Index(['id\tradius_mean\ttexture_mean\tperimeter_mean\tarea_mean\tsmoothness_mean\tcompactness_mean\tconcavity_mean\tconcave points_mean\tsymmetry_mean\tfractal_dimension_mean\tradius_se\ttexture_se\tperimeter_se\tarea_se\tsmoothness_se\tcompactness_se\tconcavity_se\tconcave points_se\tsymmetry_se\tfractal_dimension_se\tradius_worst\ttexture_worst\tperimeter_worst\tarea_worst\tsmoothness_worst\tcompactness_worst\tconcavity_worst\tconcave points_worst\tsymmetry_worst\tfractal_dimension_worst\tdiagnosis'], dtype='object')
Shape of X: (569, 31)
Shape of y: (569,)


In [96]:
print(X_train)

           id radius_mean texture_mean perimeter_mean area_mean  \
68     859471       9.029        17.33          58.79     250.5   
181    873593       21.09        26.57          142.7      1311   
63     859196       9.173        13.86           59.2     260.9   
248  88466802       10.65        25.22          68.01       347   
60     858970       10.17        14.88          64.55     311.9   
..        ...         ...          ...            ...       ...   
71     859711       8.888        14.64          58.79       244   
106    863031       11.64        18.33          75.17     412.5   
270   8910721       14.29        16.82           90.3     632.6   
435    908489       13.98        19.62          91.12     599.5   
102    862965       12.18        20.52          77.22     458.7   

    smoothness_mean compactness_mean concavity_mean concave points_mean  \
68           0.1066           0.1413          0.313             0.04375   
181          0.1141           0.2832         

In [97]:
print(X_test)

           id radius_mean texture_mean perimeter_mean area_mean  \
204     87930       12.47         18.6          81.09     481.9   
70     859575       18.94        21.31          123.6      1130   
131      8670       15.46        19.48          101.7     748.9   
431    907915        12.4        17.68          81.47     467.8   
540    921385       11.54        14.44          74.65     402.9   
..        ...         ...          ...            ...       ...   
486    913102       14.64        16.85          94.21       666   
75    8610404       16.07        19.65          104.1     817.7   
249    884689       11.52        14.93          73.87     406.3   
238    883270       14.22        27.85          92.55     623.9   
265  88995002       20.73        31.12          135.7      1419   

    smoothness_mean compactness_mean concavity_mean concave points_mean  \
204         0.09965           0.1058        0.08005             0.03821   
70          0.09009           0.1029         

In [98]:
print(y_train)

68     0
181    1
63     0
248    0
60     0
      ..
71     0
106    0
270    0
435    1
102    0
Name: diagnosis, Length: 455, dtype: object


In [112]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train.iloc[:, 6:] = sc.fit_transform(X_train.iloc[:, 6:])

X_test.iloc[:, 6:] = sc.transform(X_test.iloc[:, 6:])

In [109]:
print(X_train)

            id radius_mean texture_mean perimeter_mean area_mean  \
338     897880       10.05        17.53          64.41     310.8   
427      90745        10.8        21.98          68.79     359.9   
406     905189       16.14        14.86          104.3       800   
96       86211       12.18        17.84          77.79     451.1   
490   91376701       12.25        22.44          78.18     466.5   
..         ...         ...          ...            ...       ...   
277    8911670       18.81        19.98          120.9      1102   
9     84501001       12.46        24.04          83.97     475.9   
359  901034301       9.436        18.32          59.82     278.6   
192     875099        9.72        18.22          60.73     288.1   
559     925291       11.51        23.93          74.52     403.5   

    smoothness_mean compactness_mean concavity_mean concave points_mean  \
338          0.1007        -0.595995      -0.802596            -0.80249   
427         0.08801        -0.909

In [106]:
#Random forest
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

print("Scaling and splitting variables defined successfully.")

Scaling and splitting variables defined successfully.


In [103]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

classifier_rf = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)


classifier_rf.fit(X_train_scaled, y_train)


y_pred_rf = classifier_rf.predict(X_test_scaled)


cm_rf = confusion_matrix(y_test, y_pred_rf)
print("--- Random Forest Confusion Matrix ---")
print(cm_rf)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"\nRandom Forest Accuracy Score: {accuracy_rf*100:.2f}%")

--- Random Forest Confusion Matrix ---
[[66  1]
 [ 2 45]]

Random Forest Accuracy Score: 97.37%
